Repository devjun10/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#9 globalstyle, theme 세팅
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/Title.tsx
  Frontend/src/Title/index.tsx
  Frontend/src/Title/style.ts
  Frontend/src/index.tsx
  Frontend/src/style/global.ts
  Frontend/src/style/theme.ts
Labels: build, fe

#20 UI 구현 - IssueTable 컴포넌트
  Frontend/.eslintrc.json
  Frontend/src/IssueTable/IssueItem/index.tsx
  Frontend/src/IssueTable/IssueItem/style.ts
  Frontend/src/IssueTable/IssueList/index.tsx
  Frontend/src/IssueTable/IssueList/style.ts
  Frontend/src/IssueTable/IssueMenuBar/index.tsx
  Frontend/src/IssueTable/IssueMenuBar/style.ts
  Frontend/src/IssueTable/index.tsx
  Frontend/src/IssueTable/style.ts
  Frontend/src/common/Button/index.tsx
  Frontend/src/common/Button/style.ts
  Frontend/src/common/CheckBox/index.tsx
  Frontend/src/style/global.ts
  Frontend/src/style/theme.ts
Labels: feature, fe

#29 Fe/feature/28 UI loading
  Frontend/src/App.tsx
  Frontend/src/index.tsx
  Frontend/src/pages/Loading/index.tsx
  Frontend/src/pages/Loading/style.ts
  Frontend/src/pages/Login/style.ts
  Frontend/src/pages/Main/index.tsx
  Frontend/src/pages/Main/style.ts
  Frontend/src/router/index.tsx
  Frontend/src/style/global.ts
  Frontend/src/style/theme.ts
Labels: fe

#40 UI 구현 - 로그인 페이지, 헤더
  Frontend/public/image/user1.jpeg
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Button/style.ts
  Frontend/src/components/Header/index.tsx
  Frontend/src/components/Header/style.ts
  Frontend/src/components/IssueTable/IssueItem/index.tsx
  Frontend/src/components/IssueTable/IssueItem/style.ts
  Frontend/src/components/IssueTable/IssueList/index.tsx
  Frontend/src/components/IssueTable/IssueList/style.ts
  Frontend/src/components/IssueTable/IssueMenuBar/index.tsx
  Frontend/src/components/IssueTable/IssueMenuBar/style.ts
  Frontend/src/components/IssueTable/index.tsx
  Frontend/src/components/IssueTable/style.ts
  Frontend/src/components/UserImg/index.tsx
  Frontend/src/components/UserImg/style.ts
  Frontend/src/components/common/Button/index.tsx
  Frontend/src/components/common/Button/style.ts
  Frontend/src/components/common/CheckBox/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Login/style.ts
  Frontend/src/pages/Main/index.tsx
  Frontend/src/style/theme.ts
  Frontend/src/types/images.d.ts
  Frontend/webpack.config.js
Labels: feature, fe

#42 refactor: 전역 예외처리 로직 리펙토링
  Backend/src/main/java/com/team33/backend/common/exception/BusinessException.java
  Backend/src/main/java/com/team33/backend/common/exception/ErrorResponse.java
  Backend/src/main/java/com/team33/backend/common/exception/GlobalExceptionHandler.java
  Backend/src/main/java/com/team33/backend/common/exception/IssueTrackerRuntimeException.java
  Backend/src/main/java/com/team33/backend/common/exception/member/MemberNotFoundException.java
  Backend/src/main/java/com/team33/backend/common/exception/member/MemberRuntimeException.java
  Backend/src/test/java/com/team33/backend/common/exception/GlobalExceptionHandlerTest.java
Labels: be, refactor

#50 1주차 2번째 PR반영
  Frontend/src/components/DropDown/index.tsx
  Frontend/src/pages/Main/index.tsx
Labels: fe, refactor

#48 svgr 세팅 및 아이콘 컴포넌트구현
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/assets/icons/UserImageLarge.svg
  Frontend/src/assets/icons/UserImageSmall.svg
  Frontend/src/assets/icons/alert-circle.svg
  Frontend/src/assets/icons/archive.svg
  Frontend/src/assets/icons/calendar.svg
  Frontend/src/assets/icons/check-box-active.svg
  Frontend/src/assets/icons/check-box-disable.svg
  Frontend/src/assets/icons/check-box-initial.svg
  Frontend/src/assets/icons/check-off-circle.svg
  Frontend/src/assets/icons/check-on-circle.svg
  Frontend/src/assets/icons/edit.svg
  Frontend/src/assets/icons/milestone.svg
  Frontend/src/assets/icons/paperclip.svg
  Frontend/src/assets/icons/plus.svg
  Frontend/src/assets/icons/refresh-ccw.svg
  Frontend/src/assets/icons/search.svg
  Frontend/src/assets/icons/smile.svg
  Frontend/src/assets/icons/tag.svg
  Frontend/src/assets/icons/trash.svg
  Frontend/src/assets/icons/x-square.svg
  Frontend/src/components/Icons/index.tsx
  Frontend/src/router/index.tsx
  Frontend/src/types/custom.d.ts
  Frontend/src/types/images.d.ts
  Frontend/tsconfig.json
  Frontend/webpack.config.js
Labels: fe

#62 Filter 구현
  Frontend/src/assets/icons/bottom-arrow.svg
  Frontend/src/assets/icons/label.svg
  Frontend/src/components/DropDown/Icons/index.tsx
  Frontend/src/components/DropDown/index.tsx
  Frontend/src/components/DropDown/style.ts
  Frontend/src/components/Tap/index.tsx
  Frontend/src/components/Tap/style.ts
  Frontend/src/hooks/useMouse.tsx
  Frontend/src/pages/Login/style.ts
  Frontend/src/pages/Main/index.tsx
  Frontend/src/pages/Main/style.ts
  Frontend/src/style/theme.ts
  Frontend/src/types/styled.d.ts
Labels: feature, fe

#59 Label Component 구현
  Frontend/.eslintrc.json
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Button/style.ts
  Frontend/src/components/Icons/index.tsx
  Frontend/src/components/Label/index.tsx
  Frontend/src/components/Label/style.ts
  Frontend/src/style/global.ts
Labels: feature, fe

#66 Frontend 자동 배포 설정 추가
  .github/workflows/deploy-frontend.yml
Labels: build, fe

#70 필터 조회 및 소스 리펙토링
  Backend/src/docs/asciidoc/filter-list.adoc
  Backend/src/docs/asciidoc/index.adoc
  Backend/src/main/java/com/team33/backend/common/exception/GlobalExceptionHandler.java
  Backend/src/main/java/com/team33/backend/common/exception/issue/FilterParseException.java
  Backend/src/main/java/com/team33/backend/issue/controller/FilterController.java
  Backend/src/main/java/com/team33/backend/issue/controller/IssueController.java
  Backend/src/main/java/com/team33/backend/issue/controller/dto/filter/FilterResponse.java
  Backend/src/main/java/com/team33/backend/issue/controller/dto/issue/IssueListRequest.java
  Backend/src/main/java/com/team33/backend/issue/domain/filter/Filter.java
  Backend/src/main/java/com/team33/backend/issue/domain/filter/FilterStrategy.java
  Backend/src/main/java/com/team33/backend/issue/domain/filter/IssueFilter.java
  Backend/src/main/java/com/team33/backend/issue/domain/filter/IssueFilterStrategy.java
  Backend/src/main/java/com/team33/backend/issue/repository/IssueRepository.java
  Backend/src/main/java/com/team33/backend/issue/service/FilterService.java
  Backend/src/main/java/com/team33/backend/issue/service/IssueService.java
  Backend/src/main/resources/application-dev.yml
  Backend/src/test/java/com/team33/backend/issue/controller/FilterControllerTest.java
  Backend/src/test/java/com/team33/backend/issue/repository/IssueRepositoryTest.java
  Backend/src/test/java/com/team33/backend/issue/service/FilterServiceTest.java
  Backend/src/test/java/com/team33/backend/issue/service/IssueServiceTest.java
  Backend/src/test/resources/application.yml
  Backend/src/test/resources/sql/Issue_label_assignee-delete.sql
Labels: feature, build, be, refactor

#73 필터로 이슈 목록 조회
  Backend/src/main/java/com/team33/backend/common/exception/issue/IssueGroupNotFoundException.java
  Backend/src/main/java/com/team33/backend/issue/controller/FilterController.java
  Backend/src/main/java/com/team33/backend/issue/controller/IssueController.java
  Backend/src/main/java/com/team33/backend/issue/controller/dto/FilterListResponse.java
  Backend/src/main/java/com/team33/backend/issue/domain/filter/Filter.java
  Backend/src/main/java/com/team33/backend/issue/domain/filter/FilterStrategy.java
  Backend/src/main/java/com/team33/backend/issue/domain/filter/IssueFilter.java
  Backend/src/main/java/com/team33/backend/issue/domain/filter/IssueFilterStrategy.java
  Backend/src/main/java/com/team33/backend/issue/repository/IssueRepository.java
  Backend/src/main/java/com/team33/backend/issue/repository/query/IssueFilterQueryRepository.java
  Backend/src/main/java/com/team33/backend/issue/service/FilterService.java
  Backend/src/main/java/com/team33/backend/issue/service/IssueFilterService.java
  Backend/src/main/java/com/team33/backend/issue/service/IssueService.java
  Backend/src/test/java/com/team33/backend/issue/controller/FilterControllerTest.java
  Backend/src/test/java/com/team33/backend/issue/controller/IssueControllerTest.java
  Backend/src/test/java/com/team33/backend/issue/repository/IssueRepositoryTest.java
  Backend/src/test/java/com/team33/backend/issue/repository/IssueRepositoryUtils.java
  Backend/src/test/java/com/team33/backend/issue/repository/query/IssueFilterQueryRepositoryTest.java
  Backend/src/test/java/com/team33/backend/issue/service/FilterServiceTest.java
  Backend/src/test/java/com/team33/backend/issue/service/IssueFilterServiceTest.java
  Backend/src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
  Backend/src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-parameters.snippet
Labels: feature, be

#74 OAuth 로그인 기능 구현
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/index.tsx
  Frontend/src/pages/Loading/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/webpack.config.js
Labels: feature, fe

#78 4차 PR 리뷰 반영
  Frontend/src/components/Button/style.ts
  Frontend/src/components/DropDown/Icons/constants.ts
  Frontend/src/components/DropDown/Icons/index.tsx
  Frontend/src/components/Icons/index.tsx
  Frontend/src/components/Label/index.tsx
  Frontend/src/components/Label/style.ts
Labels: fe, refactor

#79 이슈작성 버튼 추가 및 메뉴바 css
  Frontend/src/components/DropDown/style.ts
  Frontend/src/components/Tap/style.ts
  Frontend/src/pages/Main/index.tsx
  Frontend/src/pages/Main/style.ts
  Frontend/src/style/theme.ts
Labels: feature, fe

#80 필터 컴포넌트 분리
  Frontend/src/components/DropDown/index.tsx
  Frontend/src/components/DropDown/style.ts
  Frontend/src/components/Filter/index.tsx
  Frontend/src/components/Filter/style.ts
Labels: fe, refactor

#84 Issue Table API 연동
  Frontend/src/App.tsx
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Button/style.ts
  Frontend/src/components/DropDown/Icons/index.tsx
  Frontend/src/components/Header/index.tsx
  Frontend/src/components/Icons/index.tsx
  Frontend/src/components/IssueTable/IssueItem/index.tsx
  Frontend/src/components/IssueTable/IssueList/index.tsx
  Frontend/src/components/IssueTable/IssueMenuBar/index.tsx
  Frontend/src/components/IssueTable/IssueMenuBar/style.ts
  Frontend/src/components/IssueTable/index.tsx
  Frontend/src/components/IssueTable/type.ts
  Frontend/src/components/Label/index.tsx
  Frontend/src/components/UserImg/index.tsx
  Frontend/src/components/common/Button/index.tsx
  Frontend/src/pages/Loading/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/router/index.tsx
  Frontend/webpack.config.js
Labels: feature, fe

#85 OAuth - 로그인 시 refresh token header 에 추가하여 요청
  Frontend/src/pages/Login/index.tsx
Labels: feature, fe

#88 드롭다운 클릭시 박스 펼쳐지지 않는 오류 해결
  Frontend/src/components/DropDown/index.tsx
  Frontend/src/components/DropDown/style.ts
  Frontend/src/components/Filter/index.tsx
  Frontend/src/components/Filter/style.ts
  Frontend/src/components/Tap/index.tsx
  Frontend/src/hooks/useMouse.tsx
  Frontend/src/pages/Main/index.tsx
Labels: feature, fe

#91 Filter 외에 클릭시 드롭다운 해제
  Frontend/src/components/DropDown/index.tsx
Labels: feature, fe

#94 이슈 필터 상태관리
  Frontend/src/components/DropBox/index.tsx
  Frontend/src/components/DropDown/index.tsx
  Frontend/src/components/FilterSearchBar/index.tsx
  Frontend/src/components/FilterSearchBar/style.ts
  Frontend/src/pages/Main/index.tsx
  Frontend/src/pages/Main/style.ts
Labels: feature, fe

#99 issueData, loginStatus 전역 상태 생성
  Frontend/src/App.tsx
  Frontend/src/components/Header/index.tsx
  Frontend/src/components/Header/style.ts
  Frontend/src/components/IssueTable/IssueItem/index.tsx
  Frontend/src/components/IssueTable/IssueItem/style.ts
  Frontend/src/components/IssueTable/IssueList/index.tsx
  Frontend/src/components/IssueTable/IssueList/style.ts
  Frontend/src/components/IssueTable/IssueMenuBar/index.tsx
  Frontend/src/components/IssueTable/index.tsx
  Frontend/src/components/IssueTable/style.ts
  Frontend/src/components/IssueTable/type.ts
  Frontend/src/context/CheckedIssueIdProvider.tsx
  Frontend/src/context/IssueDataProvider.tsx
  Frontend/src/context/LoginStatusProvider.tsx
  Frontend/src/pages/Loading/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Main/index.tsx
Labels: feature, fe
